package com.realmsoffate.discord;

import com.google.gson.Gson;
import com.google.gson.JsonSyntaxException;

import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.entities.Message;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;

import java.nio.charset.StandardCharsets;

import java.time.Instant;


public class ProfileSyncHandler {

    private static final long MAX_PROFILE_SIZE =
        1024L * 1024L;


    public static void handle(
        SlashCommandInteractionEvent interaction
    ) {

        if(interaction.getOption("file") == null) {

            interaction.reply(
                    "Please attach your `player.rofprofile` file."
                )
                .setEphemeral(true)
                .queue();

            return;
        }


        Message.Attachment attachment =
            interaction
                .getOption("file")
                .getAsAttachment();


        String fileName =
            attachment.getFileName();


        if(fileName == null ||
            !fileName
                .toLowerCase()
                .endsWith(".rofprofile")) {

            interaction.reply(
                    "Please upload a `.rofprofile` file generated by Realms of Fate."
                )
                .setEphemeral(true)
                .queue();

            return;
        }


        if(attachment.getSize() >
            MAX_PROFILE_SIZE) {

            interaction.reply(
                    "That profile is too large. "
                        + "`.rofprofile` files must be under 1 MB."
                )
                .setEphemeral(true)
                .queue();

            return;
        }


        interaction
            .deferReply(true)
            .queue();


        attachment
            .getProxy()
            .download()
            .whenComplete(
                (stream, error) -> {

                    if(error != null) {

                        interaction
                            .getHook()
                            .editOriginal(
                                "I could not download that profile."
                            )
                            .queue();

                        return;
                    }


                    try(
                        InputStream input = stream;

                        Reader reader =
                            new InputStreamReader(
                                input,
                                StandardCharsets.UTF_8
                            )
                    ) {

                        Gson gson =
                            new Gson();


                        RofProfileSubmission profile =
                            gson.fromJson(
                                reader,
                                RofProfileSubmission.class
                            );


                        String validationError =
                            validateProfile(
                                profile
                            );


                        if(validationError != null) {

                            interaction
                                .getHook()
                                .editOriginal(
                                    validationError
                                )
                                .queue();

                            return;
                        }


                        syncProfile(
                            interaction,
                            profile
                        );
                    }
                    catch(JsonSyntaxException exception) {

                        interaction
                            .getHook()
                            .editOriginal(
                                "That `.rofprofile` file contains invalid JSON."
                            )
                            .queue();
                    }
                    catch(Exception exception) {

                        exception.printStackTrace();

                        interaction
                            .getHook()
                            .editOriginal(
                                "Something went wrong while reading that profile."
                            )
                            .queue();
                    }
                }
            );
    }


    private static void syncProfile(
        SlashCommandInteractionEvent interaction,
        RofProfileSubmission uploadedProfile
    ) {

        BotState state =
            StateStore.load();


        String discordId =
            interaction
                .getUser()
                .getId();


        String discordName =
            interaction
                .getUser()
                .getName();


        String communityId =
            uploadedProfile
                .profile
                .communityId
                .trim();


        BotState.ProfileData linkedProfile =
            findProfileByCommunityId(
                state,
                communityId
            );


        BotState.ProfileData discordProfile =
            findProfileByDiscordId(
                state,
                discordId
            );


        /*
         * Someone else already owns this communityId.
         */
        if(linkedProfile != null &&
            linkedProfile.discordId != null &&
            !linkedProfile.discordId.equals(
                discordId
            )) {

            interaction
                .getHook()
                .editOriginal(
                    "That Realms of Fate profile is already linked "
                        + "to another Discord account."
                )
                .queue();

            return;
        }


        /*
         * This Discord account is already linked to some
         * completely different game profile.
         */
        if(discordProfile != null &&
            discordProfile.communityId != null &&
            !discordProfile.communityId.equals(
                communityId
            )) {

            interaction
                .getHook()
                .editOriginal(
                    "Your Discord account is already linked "
                        + "to a different Realms of Fate profile."
                )
                .queue();

            return;
        }


        /*
         * First upload from this player.
         */
        if(linkedProfile == null) {

            linkedProfile =
                new BotState.ProfileData();

            linkedProfile.communityId =
                communityId;

            linkedProfile.discordId =
                discordId;

            linkedProfile.discordName =
                discordName;

            linkedProfile.linkedAt =
                System.currentTimeMillis();

            linkedProfile.lastSyncAt =
                0L;

            state.profiles.add(
                linkedProfile
            );
        }


        linkedProfile.discordId =
            discordId;

        linkedProfile.discordName =
            discordName;


        if(linkedProfile.events == null) {

            linkedProfile.events =
                new java.util.ArrayList<
                    BotState.AcceptedEventProgress
                    >();
        }


        StringBuilder contributions =
            new StringBuilder();


        int changedEventCount = 0;

        int totalNewKills = 0;


        for(BotState.EventData communityEvent :
            state.events) {

            if(communityEvent == null ||
                communityEvent.eventId == null ||
                communityEvent.eventId.trim().isEmpty()) {

                continue;
            }


            int uploadedKills =
                uploadedProfile.getEventKills(
                    communityEvent.eventId
                );


            BotState.AcceptedEventProgress accepted =
                findAcceptedEventProgress(
                    linkedProfile,
                    communityEvent.eventId
                );


            int previousKills = 0;


            if(accepted != null) {

                previousKills =
                    Math.max(
                        0,
                        accepted.acceptedKills
                    );
            }


            int newKills =
                Math.max(
                    0,
                    uploadedKills -
                        previousKills
                );


            /*
             * Very important:
             *
             * If somebody uploads an older profile where
             * uploadedKills is LOWER than previously accepted,
             * we DO NOT move their accepted total backwards.
             */
            if(uploadedKills >
                previousKills) {

                if(accepted == null) {

                    accepted =
                        new BotState.AcceptedEventProgress();

                    accepted.eventId =
                        communityEvent.eventId;

                    linkedProfile.events.add(
                        accepted
                    );
                }


                accepted.acceptedKills =
                    uploadedKills;

                accepted.lastUpdatedAt =
                    System.currentTimeMillis();
            }


            if(newKills <= 0) {

                continue;
            }


            communityEvent.communityKills +=
                newKills;


            /*
             * Protect against integer overflow or
             * corrupted negative values.
             */
            if(communityEvent.communityKills < 0) {

                communityEvent.communityKills =
                    Integer.MAX_VALUE;
            }


            changedEventCount++;

            totalNewKills +=
                newKills;


            if(totalNewKills < 0) {

                totalNewKills =
                    Integer.MAX_VALUE;
            }


            if(contributions.length() > 0) {

                contributions.append(
                    "\n"
                );
            }


            String eventName =
                communityEvent.name;


            if(eventName == null ||
                eventName.trim().isEmpty()) {

                eventName =
                    communityEvent.eventId;
            }


            contributions
                .append("**")
                .append(eventName)
                .append("**\n")
                .append("+")
                .append(newKills)
                .append(" enemies defeated\n")
                .append("Your recorded total: ")
                .append(uploadedKills)
                .append("\n")
                .append("Community total: ")
                .append(
                    communityEvent.communityKills
                );


            if(communityEvent.requiredKills > 0) {

                contributions
                    .append(" / ")
                    .append(
                        communityEvent.requiredKills
                    );
            }
        }


        linkedProfile.lastSyncAt =
            System.currentTimeMillis();


        StateStore.save(
            state
        );


        /*
         * Nothing new was contributed.
         */
        if(changedEventCount == 0) {

            EmbedBuilder embed =
                new EmbedBuilder();


            embed.setTitle(
                "Profile Synced"
            );


            embed.setDescription(
                "Your Realms of Fate profile was read successfully.\n\n"
                    + "**No new community progress was found.**"
            );


            embed.addField(
                "Community ID",
                "`" + communityId + "`",
                false
            );


            embed.setFooter(
                "Your previous contributions remain recorded."
            );


            embed.setTimestamp(
                Instant.now()
            );


            interaction
                .getHook()
                .editOriginalEmbeds(
                    embed.build()
                )
                .queue();

            return;
        }


        EmbedBuilder embed =
            new EmbedBuilder();


        embed.setTitle(
            "✅ Profile Synced Successfully"
        );


        embed.setDescription(
            "Your new Realms of Fate community progress has been accepted."
        );


        embed.addField(
            "New Contribution",
            contributions.toString(),
            false
        );


        embed.addField(
            "Total New Kills",
            "+" + totalNewKills,
            true
        );


        embed.addField(
            "Events Updated",
            String.valueOf(
                changedEventCount
            ),
            true
        );


        embed.setFooter(
            "Community state saved by the Realms of Fate bot."
        );


        embed.setTimestamp(
            Instant.now()
        );


        interaction
            .getHook()
            .editOriginalEmbeds(
                embed.build()
            )
            .queue();


        System.out.println(
            "Profile sync accepted: "
                + discordName
                + " ["
                + communityId
                + "] contributed +"
                + totalNewKills
                + " kills."
        );
    }


    private static String validateProfile(
        RofProfileSubmission profile
    ) {

        if(profile == null) {

            return "That `.rofprofile` file is empty or invalid.";
        }


        if(profile.formatVersion != 1) {

            return "Unsupported `.rofprofile` format version: `"
                + profile.formatVersion
                + "`.";
        }


        if(profile.profile == null) {

            return "The profile does not contain profile information.";
        }


        if(profile.profile.communityId == null ||
            profile.profile.communityId
                .trim()
                .isEmpty()) {

            return "The profile does not contain a `communityId`.";
        }


        if(profile.profile.communityId.length() > 128) {

            return "The profile contains an invalid `communityId`.";
        }


        if(profile.events == null) {

            return "The profile does not contain event data.";
        }


        return null;
    }


    private static BotState.ProfileData
    findProfileByCommunityId(
        BotState state,
        String communityId
    ) {

        if(state.profiles == null) {

            return null;
        }


        for(BotState.ProfileData profile :
            state.profiles) {

            if(profile == null ||
                profile.communityId == null) {

                continue;
            }


            if(profile.communityId.equals(
                communityId
            )) {

                return profile;
            }
        }


        return null;
    }


    private static BotState.ProfileData
    findProfileByDiscordId(
        BotState state,
        String discordId
    ) {

        if(state.profiles == null) {

            return null;
        }


        for(BotState.ProfileData profile :
            state.profiles) {

            if(profile == null ||
                profile.discordId == null) {

                continue;
            }


            if(profile.discordId.equals(
                discordId
            )) {

                return profile;
            }
        }


        return null;
    }


    private static BotState.AcceptedEventProgress
    findAcceptedEventProgress(
        BotState.ProfileData profile,
        String eventId
    ) {

        if(profile == null ||
            profile.events == null) {

            return null;
        }


        for(
            BotState.AcceptedEventProgress progress :
            profile.events
        ) {

            if(progress == null ||
                progress.eventId == null) {

                continue;
            }


            if(progress.eventId.equalsIgnoreCase(
                eventId
            )) {

                return progress;
            }
        }


        return null;
    }
}
