package com.realmsoffate.toolkit.ui.magic;
import com.realmsoffate.toolkit.data.SpellLibraryService;import com.realmsoffate.toolkit.project.ModProject;import com.realmsoffate.toolkit.ui.ToolkitColors;import javax.swing.*;import java.awt.*;import java.io.IOException;import java.util.List;
public class MagicPanel extends JPanel{
 public interface Listener{void onNewSpell();void onOpenSpell(SpellLibraryService.SpellDefinition s);}
 private final ModProject project;private final SpellLibraryService service;private final Listener listener;private final JPanel list=new JPanel();private final JLabel count=new JLabel();
 public MagicPanel(ModProject p,SpellLibraryService s,Listener l){project=p;service=s;listener=l;setLayout(new BorderLayout(0,14));setOpaque(false);setBorder(BorderFactory.createEmptyBorder(28,32,28,32));JPanel top=new JPanel(new BorderLayout());top.setOpaque(false);JLabel title=new JLabel("Magic");title.setForeground(ToolkitColors.TEXT_PRIMARY);title.setFont(title.getFont().deriveFont(Font.BOLD,28f));JPanel left=new JPanel();left.setOpaque(false);left.setLayout(new BoxLayout(left,BoxLayout.Y_AXIS));left.add(title);left.add(new JLabel("Reusable spell definitions for Wands and Scrolls"));left.add(count);top.add(left,BorderLayout.WEST);JButton add=new JButton("+ Create Spell");add.addActionListener(e->listener.onNewSpell());top.add(add,BorderLayout.EAST);list.setLayout(new BoxLayout(list,BoxLayout.Y_AXIS));list.setBackground(ToolkitColors.BACKGROUND);JScrollPane sp=new JScrollPane(list);sp.setBorder(BorderFactory.createLineBorder(ToolkitColors.BORDER));add(top,BorderLayout.NORTH);add(sp,BorderLayout.CENTER);refresh();}
 public final void refresh(){list.removeAll();try{List<SpellLibraryService.SpellDefinition> spells=service.list(project);count.setText(spells.size()+" spells");if(spells.isEmpty()){JLabel x=new JLabel("No spells yet. Create one, then assign it to a Wand.");x.setBorder(BorderFactory.createEmptyBorder(18,18,18,18));list.add(x);}for(SpellLibraryService.SpellDefinition s:spells){JButton b=new JButton(s.getName()+"  •  "+shortClass(s.getClassName()));b.setHorizontalAlignment(SwingConstants.LEFT);b.setMaximumSize(new Dimension(Integer.MAX_VALUE,46));b.setAlignmentX(Component.LEFT_ALIGNMENT);b.addActionListener(e->listener.onOpenSpell(s));list.add(b);list.add(Box.createVerticalStrut(6));}}catch(IOException ex){count.setText("Could not load spell library");JOptionPane.showMessageDialog(this,ex.getMessage(),"Magic",JOptionPane.ERROR_MESSAGE);}list.revalidate();list.repaint();}
 private String shortClass(String c){int i=c.lastIndexOf('.');return i>=0?c.substring(i+1):c;}
}
