plugins {
    id 'java'
    id 'application'
}

group = 'com.realmsoffate'
version = '1.0.0'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

mainClassName = 'com.realmsoffate.moddingtoolkit.ModdingToolkitApp'

compileJava {
    options.encoding = 'UTF-8'
}

jar {
    baseName = 'ModdingToolkit'
    version = null
    manifest {
        attributes 'Main-Class': mainClassName
    }
}

task dist(type: Zip, dependsOn: jar) {
    baseName = 'ModdingToolkit'
    version = null
    destinationDir = file("$buildDir/distributions")
    into('ModdingToolkit') {
        from jar.archivePath
        from 'README.md'
        from 'run.bat'
        from 'run.sh'
    }
}
