package com.realmsoffate.toolkit.content.metadata;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public final class EnginePropertyScanner {

    private EnginePropertyScanner() {
    }

    public static List<PropertyDefinition> scan(
        Class<?> targetClass
    ) {

        if (targetClass == null) {

            throw new IllegalArgumentException(
                "Target class cannot be null."
            );
        }

        /*
         * LinkedHashMap prevents duplicate field names
         * while still keeping the discovered order stable.
         *
         * A child class field wins over a parent field
         * with the same name.
         */
        Map<String, PropertyDefinition> properties =
            new LinkedHashMap<String, PropertyDefinition>();

        Class<?> currentClass =
            targetClass;

        while (
            currentClass != null
                && currentClass != Object.class
        ) {

            Field[] fields =
                currentClass.getDeclaredFields();

            for (
                Field field
                : fields
            ) {

                if (
                    shouldIgnoreField(
                        field
                    )
                ) {

                    continue;
                }

                String fieldName =
                    field.getName();

                /*
                 * Child classes are scanned before parents.
                 *
                 * Therefore if this property already exists,
                 * the child version remains.
                 */
                if (
                    properties.containsKey(
                        fieldName
                    )
                ) {

                    continue;
                }

                PropertyDefinition definition =
                    new PropertyDefinition(
                        field,
                        determinePropertyType(
                            field.getType()
                        )
                    );

                properties.put(
                    fieldName,
                    definition
                );
            }

            currentClass =
                currentClass.getSuperclass();
        }

        List<PropertyDefinition> result =
            new ArrayList<PropertyDefinition>(
                properties.values()
            );

        sortProperties(
            result
        );

        return result;
    }

    private static boolean shouldIgnoreField(
        Field field
    ) {

        if (field == null) {
            return true;
        }

        int modifiers =
            field.getModifiers();

        /*
         * Static fields describe the class rather than
         * an individual item/entity instance.
         */
        if (
            Modifier.isStatic(
                modifiers
            )
        ) {

            return true;
        }

        /*
         * Synthetic fields are generated by Java itself
         * and shouldn't appear in the toolkit.
         */
        if (field.isSynthetic()) {
            return true;
        }

        return false;
    }

    private static PropertyType determinePropertyType(
        Class<?> type
    ) {

        if (type == null) {
            return PropertyType.UNKNOWN;
        }

        if (
            type == String.class
                || type == Character.class
                || type == char.class
        ) {

            return PropertyType.STRING;
        }

        if (
            type == boolean.class
                || type == Boolean.class
        ) {

            return PropertyType.BOOLEAN;
        }

        if (
            type == byte.class
                || type == Byte.class
                || type == short.class
                || type == Short.class
                || type == int.class
                || type == Integer.class
        ) {

            return PropertyType.INTEGER;
        }

        if (
            type == long.class
                || type == Long.class
        ) {

            return PropertyType.LONG;
        }

        if (
            type == float.class
                || type == Float.class
        ) {

            return PropertyType.FLOAT;
        }

        if (
            type == double.class
                || type == Double.class
        ) {

            return PropertyType.DOUBLE;
        }

        if (type.isEnum()) {

            return PropertyType.ENUM;
        }

        if (type.isArray()) {

            return PropertyType.ARRAY;
        }

        if (
            Collection.class.isAssignableFrom(
                type
            )
        ) {

            return PropertyType.COLLECTION;
        }

        if (
            Map.class.isAssignableFrom(
                type
            )
        ) {

            return PropertyType.MAP;
        }

        return PropertyType.OBJECT;
    }

    private static void sortProperties(
        List<PropertyDefinition> properties
    ) {

        Collections.sort(
            properties,
            new Comparator<PropertyDefinition>() {

                @Override
                public int compare(
                    PropertyDefinition first,
                    PropertyDefinition second
                ) {

                    String firstClass =
                        first
                            .getDeclaringClass()
                            .getName();

                    String secondClass =
                        second
                            .getDeclaringClass()
                            .getName();

                    int classComparison =
                        firstClass.compareToIgnoreCase(
                            secondClass
                        );

                    if (
                        classComparison != 0
                    ) {

                        return classComparison;
                    }

                    return first
                        .getName()
                        .compareToIgnoreCase(
                            second.getName()
                        );
                }
            }
        );
    }
}
