package com.realmsoffate.moddingtoolkit.ui;
import com.realmsoffate.moddingtoolkit.model.DocumentModel;import javax.swing.*;import javax.swing.border.*;import java.awt.*;import java.math.BigDecimal;import java.util.*;import java.util.List;

public final class FormEditor extends JPanel {
 private DocumentModel doc; private Runnable changed; private Object value; private JPanel body;
 public FormEditor(){super(new BorderLayout());setBackground(Theme.BG);}
 public void show(DocumentModel d,Object v,Runnable changed){this.doc=d;this.value=v;this.changed=changed;removeAll();body=new JPanel();body.setLayout(new BoxLayout(body,BoxLayout.Y_AXIS));body.setBackground(Theme.BG);renderContainer(body,v,"Root");JScrollPane sp=new JScrollPane(body);sp.setBorder(null);sp.getVerticalScrollBar().setUnitIncrement(18);add(sp);revalidate();repaint();}
 private void renderContainer(JPanel into,Object v,String title){
  if(v instanceof Map<?,?>){@SuppressWarnings("unchecked") Map<String,Object> map=(Map<String,Object>)v; sectionTitle(into,title,"Object · "+map.size()+" properties");for(String k:new ArrayList<>(map.keySet()))rowForMap(into,map,k);JButton add=button("+ Add Property");add.addActionListener(e->addProperty(map));into.add(wrap(add));}
  else if(v instanceof List<?>){@SuppressWarnings("unchecked") List<Object> list=(List<Object>)v;sectionTitle(into,title,"Array · "+list.size()+" values");for(int i=0;i<list.size();i++)rowForList(into,list,i);JButton add=button("+ Add Value");add.addActionListener(e->{Object nv=ValueDialog.create(this);if(nv!=ValueDialog.CANCEL){doc.checkpoint();list.add(nv);refresh();}});into.add(wrap(add));}
  else {sectionTitle(into,title,type(v));JLabel l=new JLabel(String.valueOf(v));l.setBorder(Theme.pad(12));into.add(l);}
 }
 private void rowForMap(JPanel into,Map<String,Object> map,String key){Object v=map.get(key);JPanel row=baseRow();JPanel labelBox=new JPanel();labelBox.setOpaque(false);labelBox.setLayout(new BoxLayout(labelBox,BoxLayout.Y_AXIS));JLabel name=new JLabel(FieldGuide.labelFor(key));name.setToolTipText(key);name.setFont(name.getFont().deriveFont(Font.BOLD));labelBox.add(name);JLabel help=new JLabel(FieldGuide.helpFor(key));help.setForeground(Theme.MUTED);help.setFont(help.getFont().deriveFont(11f));help.setToolTipText(FieldGuide.helpFor(key));labelBox.add(help);labelBox.setPreferredSize(new Dimension(260,40));row.add(labelBox,BorderLayout.WEST);JComponent edit=editorForKey(key,v,nv->{doc.checkpoint();map.put(key,nv);refreshIfComplex(v,nv);});row.add(edit,BorderLayout.CENTER);JButton menu=button("⋮");menu.addActionListener(e->propertyMenu(menu,map,key));row.add(menu,BorderLayout.EAST);into.add(row);if(v instanceof Map<?,?>||v instanceof List<?>){JPanel nested=nested();renderContainer(nested,v,key);into.add(nested);}}
 private void rowForList(JPanel into,List<Object> list,int idx){Object v=list.get(idx);JPanel row=baseRow();JLabel name=new JLabel("["+idx+"]");name.setPreferredSize(new Dimension(80,30));row.add(name,BorderLayout.WEST);row.add(editor(v,nv->{doc.checkpoint();list.set(idx,nv);refreshIfComplex(v,nv);}),BorderLayout.CENTER);JButton menu=button("⋮");menu.addActionListener(e->{JPopupMenu pm=new JPopupMenu();JMenuItem dup=new JMenuItem("Duplicate"),del=new JMenuItem("Delete");dup.addActionListener(x->{doc.checkpoint();list.add(idx+1,com.realmsoffate.moddingtoolkit.json.Json.deepCopy(v));refresh();});del.addActionListener(x->{doc.checkpoint();list.remove(idx);refresh();});pm.add(dup);pm.add(del);pm.show(menu,0,menu.getHeight());});row.add(menu,BorderLayout.EAST);into.add(row);if(v instanceof Map<?,?>||v instanceof List<?>){JPanel nested=nested();renderContainer(nested,v,"Value "+idx);into.add(nested);}}
 private JComponent editorForKey(String key,Object v,java.util.function.Consumer<Object> setter){
  if("tex".equalsIgnoreCase(key) && v instanceof Number){
   JPanel p=new JPanel(new BorderLayout(6,0));p.setOpaque(false);
   JComponent normal=editor(v,setter);p.add(normal,BorderLayout.CENTER);
   JButton pick=button("Pick Sprite...");pick.setToolTipText("Open a visual sprite-sheet picker. Only the numeric tex value is changed.");
   pick.addActionListener(e->{Integer n=SpritePickerDialog.choose(this,((Number)v).intValue());if(n!=null)setter.accept(new BigDecimal(String.valueOf(n)));});
   p.add(pick,BorderLayout.EAST);return p;
  }
  return editor(v,setter);
 }
 private JComponent editor(Object v,java.util.function.Consumer<Object> setter){if(v instanceof Boolean){JCheckBox c=new JCheckBox();c.setSelected((Boolean)v);c.addActionListener(e->setter.accept(c.isSelected()));return c;}if(v instanceof Map<?,?>)return muted("Object");if(v instanceof List<?>)return muted("Array ["+((List<?>)v).size()+"]");if(v==null)return muted("null");JTextField f=new JTextField(String.valueOf(v));f.addActionListener(e->commit(f,v,setter));f.addFocusListener(new java.awt.event.FocusAdapter(){public void focusLost(java.awt.event.FocusEvent e){commit(f,v,setter);}});return f;}
 private void commit(JTextField f,Object old,java.util.function.Consumer<Object> setter){try{Object n=old instanceof Number?new BigDecimal(f.getText().trim()):f.getText();if(!Objects.equals(String.valueOf(old),String.valueOf(n)))setter.accept(n);}catch(Exception ex){f.setText(String.valueOf(old));}}
 private void propertyMenu(JButton anchor,Map<String,Object> map,String key){JPopupMenu pm=new JPopupMenu();JMenuItem rename=new JMenuItem("Rename Property"),dup=new JMenuItem("Duplicate Property"),del=new JMenuItem("Delete Property");rename.addActionListener(e->{String n=JOptionPane.showInputDialog(this,"New property name",key);if(n!=null&&!n.trim().isEmpty()&&!n.equals(key)){if(map.containsKey(n)){JOptionPane.showMessageDialog(this,"That property already exists.");return;}doc.checkpoint();LinkedHashMap<String,Object> copy=new LinkedHashMap<>();for(Map.Entry<String,Object> en:map.entrySet())copy.put(en.getKey().equals(key)?n:en.getKey(),en.getValue());map.clear();map.putAll(copy);refresh();}});dup.addActionListener(e->{String n=JOptionPane.showInputDialog(this,"Duplicate property as",key+"Copy");if(n!=null&&!n.trim().isEmpty()&&!map.containsKey(n)){doc.checkpoint();map.put(n,com.realmsoffate.moddingtoolkit.json.Json.deepCopy(map.get(key)));refresh();}});del.addActionListener(e->{doc.checkpoint();map.remove(key);refresh();});pm.add(rename);pm.add(dup);pm.addSeparator();pm.add(del);pm.show(anchor,0,anchor.getHeight());}
 private void addProperty(Map<String,Object> map){String key=JOptionPane.showInputDialog(this,"Property name (example: damage, speed, manaCost)");if(key==null||key.trim().isEmpty())return;if(map.containsKey(key)){JOptionPane.showMessageDialog(this,"That property already exists.");return;}Object nv=ValueDialog.create(this);if(nv!=ValueDialog.CANCEL){doc.checkpoint();map.put(key,nv);refresh();}}
 private void refreshIfComplex(Object a,Object b){if(a instanceof Map<?,?>||a instanceof List<?>||b instanceof Map<?,?>||b instanceof List<?>)refresh();else changed.run();}
 private void refresh(){changed.run();show(doc,value,changed);}
 private JPanel baseRow(){JPanel p=new JPanel(new BorderLayout(12,0));p.setBackground(Theme.PANEL);p.setBorder(new CompoundBorder(new MatteBorder(0,0,1,0,Theme.BORDER),new EmptyBorder(8,12,8,12)));p.setMaximumSize(new Dimension(Integer.MAX_VALUE,58));return p;}
 private JPanel nested(){JPanel p=new JPanel();p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));p.setBackground(Theme.PANEL2);p.setBorder(new EmptyBorder(0,24,8,0));return p;}
 private void sectionTitle(JPanel p,String t,String sub){JPanel h=new JPanel(new BorderLayout());h.setBackground(Theme.BG);h.setBorder(new EmptyBorder(14,12,8,12));JLabel a=new JLabel(t);a.setFont(a.getFont().deriveFont(Font.BOLD,16f));JLabel b=new JLabel(sub);b.setForeground(Theme.MUTED);h.add(a,BorderLayout.WEST);h.add(b,BorderLayout.EAST);h.setMaximumSize(new Dimension(Integer.MAX_VALUE,48));p.add(h);}
 private JLabel muted(String s){JLabel l=new JLabel(s);l.setForeground(Theme.MUTED);return l;}private JButton button(String s){JButton b=new JButton(s);b.setFocusPainted(false);return b;}private JPanel wrap(JComponent c){JPanel p=new JPanel(new FlowLayout(FlowLayout.LEFT));p.setBackground(Theme.BG);p.add(c);p.setMaximumSize(new Dimension(Integer.MAX_VALUE,50));return p;}private String type(Object v){return v==null?"Null":v.getClass().getSimpleName();}
}
