package com.realmsoffate.moddingtoolkit.ui;

import com.realmsoffate.moddingtoolkit.json.Json;import com.realmsoffate.moddingtoolkit.model.DocumentModel;
import javax.swing.*;import javax.swing.event.*;import javax.swing.border.EmptyBorder;import java.awt.*;import java.awt.event.*;import java.io.*;import java.nio.file.*;import java.util.*;import java.util.List;

public final class MainFrame extends JFrame {
 private DocumentModel doc; private final DefaultListModel<Entry> entries=new DefaultListModel<>(); private final JList<Entry> entryList=new JList<>(entries); private final JTextField search=new JTextField(); private final JPanel editorHost=new JPanel(new BorderLayout()); private final JLabel status=new JLabel("Open a .json or .dat file to begin"); private final JLabel fileLabel=new JLabel("NO MOD FOLDER"); private final DefaultListModel<Category> categories=new DefaultListModel<Category>(); private final JList<Category> categoryList=new JList<Category>(categories); private Path projectRoot; private Map<ProjectScanner.Kind,List<Path>> projectFiles; private ProjectScanner.Kind currentKind; private final FormEditor form=new FormEditor(); private final JTextArea raw=new JTextArea(); private final CardLayout cards=new CardLayout(); private final JPanel cardPanel=new JPanel(cards); private Object selected; private List<Object> activeList; private String activeListKey; private boolean rawMode;
 public MainFrame(){super("ModdingToolkit — Realms of Fate");setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);setMinimumSize(new Dimension(1000,650));setSize(1400,850);setLocationRelativeTo(null);build();addWindowListener(new WindowAdapter(){public void windowClosing(WindowEvent e){if(confirmDiscard())dispose();}});}
 private void build(){setLayout(new BorderLayout());add(top(),BorderLayout.NORTH);add(center(),BorderLayout.CENTER);add(bottom(),BorderLayout.SOUTH);setJMenuBar(menu());}
 private JComponent top(){JPanel p=new JPanel(new BorderLayout());p.setBackground(Theme.PANEL);p.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createMatteBorder(0,0,1,0,Theme.BORDER),Theme.pad(12)));JLabel brand=new JLabel("REALMS OF FATE   /   MODDING TOOLKIT");brand.setFont(brand.getFont().deriveFont(Font.BOLD,17f));brand.setForeground(Theme.ACCENT);p.add(brand,BorderLayout.WEST);JPanel actions=new JPanel(new FlowLayout(FlowLayout.RIGHT,8,0));actions.setOpaque(false);actions.add(btn("Open Mod Folder",e->openProject()));actions.add(btn("Save",e->save()));actions.add(btn("Save As",e->saveAs()));p.add(actions,BorderLayout.EAST);return p;}
 private JComponent center(){JSplitPane leftSplit=new JSplitPane(JSplitPane.HORIZONTAL_SPLIT,filePane(),entryPane());leftSplit.setDividerLocation(210);leftSplit.setResizeWeight(0);JSplitPane main=new JSplitPane(JSplitPane.HORIZONTAL_SPLIT,leftSplit,editorPane());main.setDividerLocation(510);main.setResizeWeight(.28);return main;}
 private JComponent filePane(){JPanel p=panel();p.setBorder(Theme.pad(10));JLabel t=title("CONTENT");p.add(t,BorderLayout.NORTH);categoryList.setFixedCellHeight(48);categoryList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);categoryList.addListSelectionListener(e->{if(!e.getValueIsAdjusting()){Category c=categoryList.getSelectedValue();if(c!=null)openCategory(c.kind);}});p.add(new JScrollPane(categoryList),BorderLayout.CENTER);JPanel foot=new JPanel();foot.setOpaque(false);foot.setLayout(new BoxLayout(foot,BoxLayout.Y_AXIS));fileLabel.setForeground(Theme.MUTED);fileLabel.setFont(fileLabel.getFont().deriveFont(10f));foot.add(Box.createVerticalStrut(8));foot.add(fileLabel);foot.add(Box.createVerticalStrut(6));JButton advanced=btn("Open Data File...",e->open());advanced.setToolTipText("Advanced: open an individual JSON or DAT file directly.");foot.add(advanced);p.add(foot,BorderLayout.SOUTH);return p;}
 private JComponent entryPane(){JPanel p=panel();JPanel n=new JPanel(new BorderLayout(0,8));n.setOpaque(false);n.setBorder(Theme.pad(12));n.add(title("CONTENT LIST"),BorderLayout.NORTH);search.putClientProperty("JTextField.placeholderText","Search entries...");n.add(search,BorderLayout.CENTER);p.add(n,BorderLayout.NORTH);entryList.setBorder(new EmptyBorder(4,8,4,8));entryList.setFixedCellHeight(34);entryList.addListSelectionListener(e->{if(!e.getValueIsAdjusting()){Entry en=entryList.getSelectedValue();if(en!=null){selected=en.value;showSelected();}}});p.add(new JScrollPane(entryList),BorderLayout.CENTER);JPanel buttons=new JPanel(new GridLayout(1,3,6,0));buttons.setOpaque(false);buttons.setBorder(Theme.pad(8));buttons.add(btn("+ New",e->addEntry()));buttons.add(btn("Duplicate",e->duplicateEntry()));buttons.add(btn("Delete",e->deleteEntry()));p.add(buttons,BorderLayout.SOUTH);search.getDocument().addDocumentListener(new DocumentListener(){public void insertUpdate(DocumentEvent e){reloadEntries();}public void removeUpdate(DocumentEvent e){reloadEntries();}public void changedUpdate(DocumentEvent e){reloadEntries();}});return p;}
 private JComponent editorPane(){JPanel p=panel();JPanel head=new JPanel(new BorderLayout());head.setOpaque(false);head.setBorder(Theme.pad(10));head.add(title("EDITOR"),BorderLayout.WEST);JPanel modes=new JPanel(new FlowLayout(FlowLayout.RIGHT,5,0));modes.setOpaque(false);modes.add(btn("Form",e->{applyRawIfNeeded();rawMode=false;cards.show(cardPanel,"form");showSelected();}));modes.add(btn("Raw JSON",e->{rawMode=true;raw.setText(Json.pretty(selected!=null?selected:doc==null?new LinkedHashMap<>():doc.root()));raw.setCaretPosition(0);cards.show(cardPanel,"raw");}));modes.add(btn("Apply Raw",e->applyRaw()));head.add(modes,BorderLayout.EAST);p.add(head,BorderLayout.NORTH);cardPanel.add(form,"form");raw.setFont(new Font(Font.MONOSPACED,Font.PLAIN,14));raw.setTabSize(2);cardPanel.add(new JScrollPane(raw),"raw");p.add(cardPanel,BorderLayout.CENTER);return p;}
 private JComponent bottom(){JPanel p=new JPanel(new BorderLayout());p.setBackground(Theme.PANEL);p.setBorder(new EmptyBorder(7,12,7,12));status.setForeground(Theme.MUTED);p.add(status,BorderLayout.WEST);JLabel safe=new JLabel("SAFE SAVE + AUTOMATIC BACKUP");safe.setForeground(Theme.MUTED);p.add(safe,BorderLayout.EAST);return p;}
 private JMenuBar menu(){JMenuBar b=new JMenuBar();JMenu file=new JMenu("File"),edit=new JMenu("Edit");JMenuItem open=new JMenuItem("Open…"),save=new JMenuItem("Save"),saveAs=new JMenuItem("Save As…"),exit=new JMenuItem("Exit"),undo=new JMenuItem("Undo"),redo=new JMenuItem("Redo");open.addActionListener(e->open());save.addActionListener(e->save());saveAs.addActionListener(e->saveAs());exit.addActionListener(e->{if(confirmDiscard())dispose();});undo.addActionListener(e->{if(doc!=null){doc.undo();reloadAll();}});redo.addActionListener(e->{if(doc!=null){doc.redo();reloadAll();}});file.add(open);file.add(save);file.add(saveAs);file.addSeparator();file.add(exit);edit.add(undo);edit.add(redo);b.add(file);b.add(edit);return b;}
 private void openProject(){if(!confirmDiscard())return;JFileChooser fc=new JFileChooser();fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);fc.setDialogTitle("Choose your Realms of Fate mod / data folder");if(fc.showOpenDialog(this)!=JFileChooser.APPROVE_OPTION)return;try{projectRoot=fc.getSelectedFile().toPath();projectFiles=ProjectScanner.scan(projectRoot);categories.clear();addCategory(ProjectScanner.Kind.ITEMS,"ITEMS","Create and edit weapons, armor, potions and other items");addCategory(ProjectScanner.Kind.MONSTERS,"MONSTERS","Create and edit enemies and creatures");addCategory(ProjectScanner.Kind.SPELLS,"SPELLS","Edit spell data");addCategory(ProjectScanner.Kind.LEVELS,"LEVELS","Browse level data");addCategory(ProjectScanner.Kind.OTHER,"OTHER DATA","Advanced game data");fileLabel.setText(projectRoot.getFileName().toString());status.setText("Choose Items, Monsters, Spells, or Levels");doc=null;entries.clear();selected=null;form.removeAll();}catch(Exception ex){error("Could not scan mod folder",ex);}}
 private void addCategory(ProjectScanner.Kind kind,String name,String help){int count=projectFiles==null?0:projectFiles.get(kind).size();categories.addElement(new Category(kind,name,help,count));}
 private void openCategory(ProjectScanner.Kind kind){if(projectFiles==null)return;if(doc!=null&&doc.dirty()&&!confirmDiscard()){categoryList.clearSelection();return;}List<Path> paths=projectFiles.get(kind);if(paths==null||paths.isEmpty()){JOptionPane.showMessageDialog(this,"No "+friendly(kind)+" data file was found in this folder.\n\nYou can still use 'Open Data File...' for an unusual mod layout.",friendly(kind),JOptionPane.INFORMATION_MESSAGE);return;}Path chosen=paths.get(0);if(paths.size()>1){Object pick=JOptionPane.showInputDialog(this,"More than one matching data file was found:",friendly(kind),JOptionPane.PLAIN_MESSAGE,null,paths.toArray(),paths.get(0));if(!(pick instanceof Path))return;chosen=(Path)pick;}try{doc=DocumentModel.open(chosen);currentKind=kind;selected=null;reloadAll();}catch(Exception ex){error("Could not open "+friendly(kind),ex);}}
 private String friendly(ProjectScanner.Kind k){switch(k){case ITEMS:return "Items";case MONSTERS:return "Monsters";case SPELLS:return "Spells";case LEVELS:return "Levels";default:return "Other Data";}}
 private void open(){if(!confirmDiscard())return;JFileChooser fc=new JFileChooser();fc.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("JSON / Delver data (*.json, *.dat)","json","dat"));if(fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)try{doc=DocumentModel.open(fc.getSelectedFile().toPath());selected=null;reloadAll();}catch(Exception ex){error("Could not open file",ex);}}
 private void save(){if(doc==null)return;if(rawMode&&!applyRawIfNeeded())return;try{doc.save();updateStatus("Saved "+doc.path().getFileName());}catch(Exception ex){error("Could not save file",ex);}}
 private void saveAs(){if(doc==null)return;if(rawMode&&!applyRawIfNeeded())return;JFileChooser fc=new JFileChooser();fc.setSelectedFile(doc.path().toFile());if(fc.showSaveDialog(this)==JFileChooser.APPROVE_OPTION)try{doc.saveAs(fc.getSelectedFile().toPath());reloadAll();}catch(Exception ex){error("Could not save file",ex);}}
 private void reloadAll(){if(doc==null)return;fileLabel.setText(doc.path().getFileName().toString());discoverEntries();reloadEntries();if(selected==null){if(entries.size()>0)entryList.setSelectedIndex(0);else{selected=doc.root();showSelected();}}updateStatus(doc.dirty()?"● Unsaved changes":"✓ Valid JSON");}
 private void discoverEntries(){activeList=null;activeListKey=null;Object root=doc.root();if(root instanceof List<?>){activeList=castList((List<?>)root);return;}if(root instanceof Map<?,?>){Map<?,?> m=(Map<?,?>)root;int best=-1;for(Map.Entry<?,?> e:m.entrySet()){if(e.getValue() instanceof List<?>){List<?> l=(List<?>)e.getValue();if(l.size()>best){best=l.size();activeList=castList(l);activeListKey=String.valueOf(e.getKey());}}}}}
 @SuppressWarnings("unchecked") private List<Object> castList(List<?> l){return (List<Object>)l;}
 private void reloadEntries(){entries.clear();if(doc==null)return;String q=search.getText().trim().toLowerCase();if(activeList==null){entries.addElement(new Entry("Document Root",doc.root(),-1));return;}for(int i=0;i<activeList.size();i++){Object v=activeList.get(i);String name=entryName(v,i);if(q.isEmpty()||name.toLowerCase().contains(q))entries.addElement(new Entry(name,v,i));} }
 private String entryName(Object v,int i){if(v instanceof Map<?,?>){Map<?,?> m=(Map<?,?>)v;for(String k:new String[]{"name","id","key","type","itemType","class"}){Object x=m.get(k);if(x!=null&&!String.valueOf(x).trim().isEmpty())return String.valueOf(x);} }return "Entry "+i+"  ·  "+type(v);}
 private void showSelected(){if(doc==null||selected==null)return;if(rawMode){raw.setText(Json.pretty(selected));raw.setCaretPosition(0);}else form.show(doc,selected,this::onChanged);updateStatus(doc.dirty()?"● Unsaved changes":"✓ Valid JSON");}
 private void onChanged(){discoverEntries();reloadEntries();updateStatus("● Unsaved changes");}
 private void addEntry(){if(doc==null)return;if(activeList==null){JOptionPane.showMessageDialog(this,"This document does not expose an entry array. Use the form editor to add values to its structure.");return;}Object nv=createFriendlyEntry();if(nv==ValueDialog.CANCEL)return;doc.checkpoint();activeList.add(nv);selected=nv;reloadAll();selectByIdentity(nv);}
 private Object createFriendlyEntry(){if(currentKind==ProjectScanner.Kind.ITEMS||currentKind==ProjectScanner.Kind.MONSTERS||currentKind==ProjectScanner.Kind.SPELLS){String label=currentKind==ProjectScanner.Kind.ITEMS?"item":currentKind==ProjectScanner.Kind.MONSTERS?"monster":"spell";String name=JOptionPane.showInputDialog(this,"Name for the new "+label+":","New "+Character.toUpperCase(label.charAt(0))+label.substring(1),JOptionPane.PLAIN_MESSAGE);if(name==null)return ValueDialog.CANCEL;if(name.trim().isEmpty())name="New "+Character.toUpperCase(label.charAt(0))+label.substring(1);LinkedHashMap<String,Object> m=new LinkedHashMap<String,Object>();m.put("name",name.trim());return m;}return ValueDialog.create(this);}
 private void duplicateEntry(){Entry en=entryList.getSelectedValue();if(doc==null||activeList==null||en==null||en.index<0)return;doc.checkpoint();Object copy=Json.deepCopy(en.value);activeList.add(Math.min(en.index+1,activeList.size()),copy);selected=copy;reloadAll();selectByIdentity(copy);}
 private void deleteEntry(){Entry en=entryList.getSelectedValue();if(doc==null||activeList==null||en==null||en.index<0)return;if(JOptionPane.showConfirmDialog(this,"Delete \""+en.name+"\"?\n\nReferences elsewhere will not be removed automatically.","Delete entry",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE)!=JOptionPane.OK_OPTION)return;doc.checkpoint();activeList.remove(en.index);selected=null;reloadAll();}
 private void selectByIdentity(Object o){for(int i=0;i<entries.size();i++)if(entries.get(i).value==o){entryList.setSelectedIndex(i);break;}}
 private void applyRaw(){if(doc==null)return;try{Object parsed=Json.parse(raw.getText());doc.checkpoint();if(selected==doc.root()){doc.setRoot(parsed);selected=doc.root();}else if(!replaceSelected(parsed))throw new IllegalStateException("Selected value could not be located in its entry array.");selected=parsed;raw.setText(Json.pretty(parsed));reloadAll();updateStatus("✓ Raw JSON applied");}catch(Exception ex){error("Invalid JSON",ex);}}
 private boolean replaceSelected(Object parsed){if(activeList!=null)for(int i=0;i<activeList.size();i++)if(activeList.get(i)==selected){activeList.set(i,parsed);return true;}return false;}
 private boolean applyRawIfNeeded(){if(!rawMode||doc==null)return true;try{Json.parse(raw.getText());return true;}catch(Exception ex){int r=JOptionPane.showConfirmDialog(this,"Raw JSON is invalid. Discard those raw edits?\n\n"+ex.getMessage(),"Invalid JSON",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);return r==JOptionPane.YES_OPTION;}}
 private boolean confirmDiscard(){if(doc==null||!doc.dirty())return true;int r=JOptionPane.showConfirmDialog(this,"There are unsaved changes. Discard them?","Unsaved changes",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);return r==JOptionPane.YES_OPTION;}
 private void updateStatus(String s){status.setText(s+(activeListKey==null?"":"   •   entries: "+activeListKey));}
 private JPanel panel(){JPanel p=new JPanel(new BorderLayout());p.setBackground(Theme.PANEL);return p;}private JLabel title(String s){JLabel l=new JLabel(s);l.setFont(l.getFont().deriveFont(Font.BOLD,12f));l.setForeground(Theme.MUTED);return l;}private JButton btn(String s,ActionListener a){JButton b=new JButton(s);b.setFocusPainted(false);b.addActionListener(a);return b;}private void error(String title,Exception e){JOptionPane.showMessageDialog(this,e.getMessage(),title,JOptionPane.ERROR_MESSAGE);}private String type(Object o){return o==null?"null":o instanceof Map?"object":o instanceof List?"array":o.getClass().getSimpleName().toLowerCase();}
 private static final class Category{final ProjectScanner.Kind kind;final String name,help;final int count;Category(ProjectScanner.Kind k,String n,String h,int c){kind=k;name=n;help=h;count=c;}public String toString(){return name+(count>0?"   ("+count+")":"");}}
 private static final class Entry{final String name;final Object value;final int index;Entry(String name,Object value,int index){this.name=name;this.value=value;this.index=index;}public String toString(){return name;}}
}
